### ISSUE TITLE
Possible to attach post-save hooks using the fluent API?

### ISSUE THREAD

**Issue by rtybanana** [dombrovsky/EntityHooks#14]
Hi @dombrovsky,

I see a few references to post-save hooks in the source code, but I don't see any way of attaching them using the fluent API. Is this possible with the current API or, if not, do you think it would be possible to add the functionality myself? Or is it infeasible?

Many thanks,
Rory

**Comment by dombrovsky** [comment]
Hi @rtybanana 
Yes, with fluent API right now it is only possible to attach Load and Pre-save hooks. That is because fluent API was originally designed to be attached to any DbContext, and DbContext base class does not provide any event that post save hook can be attached to.
Post-save hooks can be used only when deriving from [DbHookContext](https://github.com/dombrovsky/EntityHooks/blob/master/src/System.Data.Entity.Hooks/DbHookContext.cs).
If you are ok with deriving from DbHookContext, but still want to use fluent API to register your post-save hooks, it may be possible with a slight modification: `IDbHookRegistrar.RegisterPostSaveHook` has to be added with some additional methods to Fluent API. `DbContextHooker.RegisterPostSaveHook` would have to throw InvalidOprationException.
If you would like to submit PR for that change I would appreciate. If not, I may consider adding that myself.

**Comment by rtybanana** [comment]
Hi @dombrovsky,

Appreciate the swift response. Unfortunately, I am unable to derive from the DbHookContext because I'm already derived from another class. I've switched to using a different package and I'm currently working on a workaround to get that one working as I would like. 

Thanks anyway.
